# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15525c9f8c2fc12115e0df5b9f55d891bf7ed86ab7184c5c73a1e1b6298180198d1faa919e9e0cb5ca021e056d5ee05f7e4d1e73186a4bdfd6ea60f0d4b7b999

test:
  secret_key_base: 9996226f93ec2021e8ee853144a075d27ba9f5d3b0c4a7123110d10ac2b0d584c4dd774bfb0c57abd93ac443f6e9ef6d551ac7a2ad764661502d87ce7580c784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
